name: Generate PlantUML Diagrams
on:
  pull_request
jobs:
  plantuml:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".plantuml"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: dorny/paths-filter@v2
        name:  "Get PlantUML files"
        id: filter
        with:
          list-files: 'shell'
          base: 'main'
          filters: |
            puml:
            - '**.plantuml'
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        if: steps.filter.outputs.puml == 'true'
        with:
            args: -v -tpng ${{ steps.filter.outputs.puml_files }}
      - name: Create Pull Request if PNG(s) were produced
        if: steps.filter.outputs.puml == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Code formatting tool on ${{ github.head_ref }}
          title: PlantUML PNG(s) for ${{ github.head_ref }}
          body: Auto-generated PR with generated PlantUML PNG(s)
          labels: automated pr
          branch: plantuml-png/${{ github.head_ref }}            
