name: Generate PlantUML Diagrams
on:
  pull_request
jobs:
  plantuml:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".plantuml"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: dorny/paths-filter@v2
        name:  "Get PlantUML files"
        id: filter
        with:
          list-files: 'shell'
          base: 'main'
          filters: |
            puml:
            - '**.plantuml'
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        if: steps.filter.outputs.puml == 'true'
        with:
            args: -v -tpng ${{ steps.filter.outputs.puml_files }}
      - name: Push Local Changes
        if: steps.filter.outputs.puml == 'true'
        uses:  stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: "Generate PNG images for PlantUML diagrams" 
